//! NTDS tactical-symbol geometry and outline icon font.
//!
//! `ntds-icons` packages the Naval Tactical Data System symbol set as a
//! standalone, bevy-free, font-first crate:
//!
//! - [`shapes`] — pure-geometry [`shapes::ShapeCmd`] descriptions of every NTDS
//!   symbol (zero dependencies), for direct drawing (map gizmos, SVG export).
//! - [`layout`] — the single source of truth for the glyph set and its PUA
//!   codepoint assignment.
//! - [`codepoints`] — `char`-returning glyph lookups on the crate's own enums.
//!
//! - [`build`] (feature `build`) — the font generator: `build_font`, WOFF2, and
//!   specimen rendering. Pulls kurbo/write-fonts; off by default.
//!
pub mod codepoints;
pub mod layout;
pub mod shapes;

#[cfg(feature = "build")]
pub mod build;

/// The pre-built NTDS icon font (TrueType).
///
/// Generated by [`build::build_font`] under the `build` feature and committed;
/// byte-identical to a fresh build (enforced by the drift test). Every geometry
/// and metric table is byte-identical to dronecom's in-game font — only the
/// `name` table differs (no `DroneCarrier-` branding).
pub const FONT_TTF: &[u8] = include_bytes!("../assets/ntds_icons.ttf");
